views:
  telnetConnected:
    ansi: connected

  sshConnected:
    ansi: connected
    next:
      view: authWelcome
      delay: 1000
#    next: authWelcome
#    next:
#    - view: authSshSecondFactor # require 2FA
#      acs: AR2
#    - view: demo # this drops a user into the demo view
#      acs: GM[demo]
#    - view: authWelcome

  authWelcome:
    ansi: _welcome
    next: interstitial
    config:
      prompt: pause

prompts:
  pause:
    ansi: pause
    lineFeed: no